general README updates, as well intermediate DoD cert directions
dod-ccpo/authnid pull request #18
Opened 2018-06-20 16:10 UTC by dandds

This updates the README to refer to the scripts-to-rule-them-all and adds directions for adding DoD intermediate certs to the CA bundle. This will change pending resolution of [this](https://www.pivotaltracker.com/n/projects/2160940/stories/158497124) Pivotal discussion.

2018-06-20 17:28 UTC, briandds commented on README.md
> +To build, run `script/sertup`.  `script/server` starts the stack with Docker Compose:
`sertup` -> `setup`?

2018-06-20 18:10 UTC, ddsdevon commented on README.md
> +To build, run `script/sertup`.  `script/server` starts the stack with Docker Compose:
Er mah gerd, sertup!

2018-06-20 19:13 UTC, dandds commented on README.md
> +To build, run `script/sertup`.  `script/server` starts the stack with Docker Compose:
whoops, fixed

2018-06-21 12:56 UTC, dandds commented
Rebased to get the test passing after merging https://github.com/dod-ccpo/authnid/pull/19. I knew something was up when a README change broke CI...

2018-06-21 16:54 UTC, jordangov requested changes

2018-06-21 16:54 UTC, jordangov commented on README.md
> +note: add info about the intermediate CAs
looks like we have the note?

2018-06-21 17:10 UTC, dandds commented on README.md
> +note: add info about the intermediate CAs
yup, fixed.

2018-06-21 19:23 UTC, jordangov approved these changes

2018-06-21 20:28 UTC, merged